Upgrade to php 8.3 and remove php 8.0 as a dependency.
laminas-api-tools/api-tools-api-problem pull request #25
Opened 2024-02-11 23:46 UTC by datasage

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes/no
| BC Break      | yes
| New Feature   | no
| RFC           | no
| QA            | no

### Description
Add PHP 8.3 as a supported version and removed php 8.0 as a supported version.

Included is an update to phpunit 10.x and psalm 5.x.

All the required packages were updated to the minimum version that matched the php version requirments

2024-04-18 08:27 UTC, InstantlyMoist commented
merge and release
merge and release
merge and release

2024-04-18 08:38 UTC, samsonasik commented on src/ApiProblem.php
> +    protected array $additionalDetails = [];
This is BC break, please revert, see https://3v4l.org/q5UKJ

2024-04-18 08:38 UTC, samsonasik commented on src/ApiProblem.php
> +    protected string|Exception|Throwable $detail = '';
Also please revert

2024-04-18 08:40 UTC, samsonasik commented on src/ApiProblem.php
> +    protected function getDetail(): string
please revert; bc break, see https://3v4l.org/plECe

2024-04-18 08:41 UTC, samsonasik requested changes
Please revert `ApiProblem` change as bc break

2024-04-26 03:20 UTC, datasage commented
@samsonasik Removed most of the type hints for now. Understand the concern about compatibility.

2024-04-26 05:27 UTC, samsonasik commented on src/ApiProblem.php
> +    protected array $problemStatusTitles = [
Did you push the change? This is Bc Break

2024-04-26 14:32 UTC, kersysgediminas commented on src/ApiProblem.php
> +    protected function getDetail(): string
@datasage Please revert

2024-04-30 13:41 UTC, kersysgediminas commented
@samsonasik All requested changes were made, please review.

2024-04-30 13:47 UTC, samsonasik commented
CI failure https://github.com/laminas-api-tools/api-tools-api-problem/actions/runs/8852932653/job/24427217125?pr=25#step:3:76

2024-05-13 12:59 UTC, svycka commented
Hello @datasage, do you plan to update this PR? Do you need any help?

2024-05-13 15:14 UTC, datasage commented
All CI checks are passing now

2024-05-13 15:19 UTC, samsonasik commented on composer.json
> -            "php": "8.0.99"
this may need to use 8.1.99 for consistency

2024-05-14 00:36 UTC, samsonasik commented
composer.lock need to be regenerated

2024-05-14 02:10 UTC, samsonasik approved these changes

2024-06-05 06:51 UTC, kersysgediminas approved these changes

2024-07-15 15:55 UTC, marc-mabe commented
Any chance this could be merged? It's the last blocker for upgrading to PHP 8.3 for me

2024-07-15 16:00 UTC, InstantlyMoist commented
> Any chance this could be merged? It's the last blocker for upgrading to PHP 8.3 for me

Waiting for it too, I did notice this though: https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2024-05-06-TSC-Minutes.md#api-tools-related-proposed-by-dotkernel-organisation

As far as I understand it, the Laminas API tools might get deprecated

2024-07-15 16:05 UTC, marc-mabe commented
> As far as I understand it, the Laminas API tools might get deprecated

If it's deprecated it's deprecated - no question - but right now it's not

2024-07-15 16:11 UTC, Xerkus commented
API Tools are currently on security only maintenance mode and PHP 8.3 support is not planned.

I expect API Tools to be entirely discontinued with Dotkernel API as a replacement based on Mezzio: https://getlaminas.org/blog/2024-07-02-dotkernel-a-replacement-for-laminas-api-tools.html

2026-08-08 15:32 UTC, closed without merging